name: APK Olusturucu
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Buildozer ile APK Yap
        uses: ArtemSBulgakov/buildozer-action@v1
        with:
          workdir: .
          buildozer_version: master
      - name: APK Dosyasini Yukle
        uses: actions/upload-artifact@v2
        with:
          name: Satranc-Saati-APK
          path: bin/*.apk
